#### crowsnest.conf
#### This is the default config after installation.
#### It is also used as the default config in MainsailOS.
#### For details on how to configure this to your needs, see:
#### https://github.com/mainsail-crew/crowsnest/blob/v5/README.md


#####################################################################
####                                                            #####
####      Information about ports and according URL's           #####
####                                                            #####
#####################################################################
####                                                            #####
####    Port 8080 equals /webcam/?action=[stream/snapshot]      #####
####    Port 8081 equals /webcam2/?action=[stream/snapshot]     #####
####    Port 8082 equals /webcam3/?action=[stream/snapshot]     #####
####    Port 8083 equals /webcam4/?action=[stream/snapshot]     #####
####                                                            #####
####    Note: These ports are default for most Mainsail         #####
####    installations. Using any other port would involve       #####
####    changing the proxy configuration or using URLs          #####
####    with the specific port like                             #####
####    http://<ip>:<port>/?action=[stream/snapshot]            #####
####                                                            #####
#####################################################################


[crowsnest]
log_level: verbose                      # Valid Options are quiet/verbose/debug
rollover_on_start: false                # Creates a backup and clears the log on every restart, if set to true
no_proxy: false                         # If set to true, no reverse proxy is required. Only change this, if you know what you are doing.

[cam 1]
#mode: spyglass                         # https://docs.mainsail.xyz/crowsnest/faq/backends
mode: camera-streamer                         # https://docs.mainsail.xyz/crowsnest/faq/backends
port: 8080                              # HTTP/MJPG stream/snapshot port
device: /base/soc/i2c0mux/i2c@1/ov5647@36                     # See log for available devices
resolution: 1296x972                     # <width>x<height> format
max_fps: 10                             # If hardware supports it, it will be forced, otherwise ignored/coerced.
#custom_flags:  -ud                        # You can run the stream services with custom flags.
custom_flags:  --camera-vflip=1 --camera-hflip=1                        # You can run the stream services with custom flags.
v4l2ctl:  ExposureValue=-1.5,AeMeteringMode=2,AeEnable=1,AwbMode=0,videobitrate=5000000                             # Add v4l2-ctl parameters to set up your camera, see log for your camera capabilities.
