[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/pi/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    192.168.0.0/16
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FC00::/7
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[octoprint_compat]

[history]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager fluidd]
path: /home/pi/fluidd
repo: fluidd-core/fluidd
channel: stable
type: web
persistent_files:
    config.json

[update_manager fluidd-config]
managed_services: klipper
origin: https://github.com/fluidd-core/fluidd-config.git
path: /home/pi/fluidd-config
primary_branch: master
type: git_repo

[update_manager KlipperScreen]
install_script: /home/pi/KlipperScreen/scripts/KlipperScreen-install.sh
requirements: /home/pi/KlipperScreen/scripts/KlipperScreen-requirements.txt
env: /home/pi/.KlipperScreen-env/bin/python
managed_services: KlipperScreen
origin: https://github.com/KlipperScreen/KlipperScreen.git
path: /home/pi/KlipperScreen
type: git_repo

[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
primary_branch: v5
managed_services: crowsnest
system_dependencies: system-dependencies.json
virtualenv: ~/crowsnest-env
requirements: requirements.txt

[update_manager Klipper-Adaptive-Meshing-Purging]
type: git_repo
channel: dev
path: /home/pi/Klipper-Adaptive-Meshing-Purging
origin: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services: klipper
primary_branch: main

[spoolman]
server: http://192.168.72.110:7912
sync_rate: 5

[file_manager]
enable_object_processing: True

[analysis]
enable_auto_analysis: true
enable_estimator_updates: true

[power printer_momentary]
type: gpio
pin: gpiochip0/gpio26
locked_while_printing: True
timer: 1
restart_klipper_when_powered: True
